# macOS-specific
font_size 14.0
symbol_map U+1F300-U+1F6FF Apple Color Emoji
macos_option_as_alt left
macos_quit_when_last_window_closed yes
macos_traditional_fullscreen no
macos_show_window_title_in none
macos_hide_titlebar yes
