# =============================================================================
# HYPRSUNSET — filtro de luz azul
# =============================================================================

# --- Día ---------------------------------------------------------------------
profile {
    time = 9:00
    identity = true
}

# --- Noche -------------------------------------------------------------------
profile {
    time = 19:30
    temperature = 5200
}
