[mgr]
keymap = [
  # Navegación
  { on = [ "j" ], run = "arrow 1", desc = "Move cursor down" },
  { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
  { on = [ "h" ], run = "leave", desc = "Go to parent directory" },
  { on = [ "l" ], run = "enter", desc = "Enter directory or open file" },
  
  { on = [ "J" ], run = "arrow 5", desc = "Move cursor down 5 lines" },
  { on = [ "K" ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  
  { on = [ "g", "g" ], run = "arrow -99999999", desc = "Go to the first" },
  { on = [ "G" ], run = "arrow 99999999", desc = "Go to the last" },
  
  # Navegación por pestañas (similar a Neovim)
  { on = [ "<Tab>" ], run = "tab_switch 1", desc = "Switch to next tab" },
  { on = [ "<S-Tab>" ], run = "tab_switch -1", desc = "Switch to previous tab" },
  { on = [ "<C-t>" ], run = "tab_create --current", desc = "Create a new tab" },
  { on = [ "<C-w>" ], run = "close", desc = "Close current tab" },
  { on = [ "1" ], run = "tab_switch 0", desc = "Switch to tab 1" },
  { on = [ "2" ], run = "tab_switch 1", desc = "Switch to tab 2" },
  { on = [ "3" ], run = "tab_switch 2", desc = "Switch to tab 3" },
  { on = [ "4" ], run = "tab_switch 3", desc = "Switch to tab 4" },
  { on = [ "5" ], run = "tab_switch 4", desc = "Switch to tab 5" },
  
  # Operaciones con archivos
  { on = [ "<Space>" ], run = "select --state=none", desc = "Toggle selection" },
  { on = [ "v" ], run = "visual_mode", desc = "Enter visual mode" },
  { on = [ "V" ], run = "visual_mode --unset", desc = "Exit visual mode" },
  { on = [ "<C-a>" ], run = "select_all --state=true", desc = "Select all" },
  { on = [ "<C-r>" ], run = "select_all --state=none", desc = "Inverse selection" },
  
  { on = [ "o" ], run = "open", desc = "Open selected files" },
  { on = [ "O" ], run = "open --interactive", desc = "Open selected files interactively" },
  { on = [ "<Enter>" ], run = "open", desc = "Open selected files" },
  { on = [ "<C-Enter>" ], run = "open --interactive", desc = "Open selected files interactively" },
  
  # Copiar/Cortar/Pegar (similar a vim)
  { on = [ "y", "y" ], run = "yank", desc = "Yank selected files" },
  { on = [ "d", "d" ], run = "yank --cut", desc = "Cut selected files" },
  { on = [ "p" ], run = "paste", desc = "Paste yanked files" },
  { on = [ "P" ], run = "paste --force", desc = "Paste yanked files (overwrite)" },
  { on = [ "D" ], run = "remove", desc = "Delete selected files" },
  { on = [ "x" ], run = "remove --permanently", desc = "Delete permanently" },
  
  # Renombrar
  { on = [ "r" ], run = "rename", desc = "Rename" },
  { on = [ "R" ], run = "bulk_rename", desc = "Bulk rename" },
  
  # Crear archivos/directorios
  { on = [ "a" ], run = "create", desc = "Create file/directory" },
  { on = [ "A" ], run = "create --dir", desc = "Create directory" },
  
  # Búsqueda (similar a fzf en Neovim)
  { on = [ "/" ], run = "find --smart", desc = "Find" },
  { on = [ "?" ], run = "find --previous --smart", desc = "Find previous" },
  { on = [ "n" ], run = "find_arrow", desc = "Go to next found" },
  { on = [ "N" ], run = "find_arrow --previous", desc = "Go to previous found" },
  { on = [ "f", "f" ], run = "filter --smart", desc = "Filter files" },
  
  # Ordenamiento
  { on = [ ",", "n" ], run = "sort natural --dir-first", desc = "Sort naturally" },
  { on = [ ",", "N" ], run = "sort natural --reverse --dir-first", desc = "Sort naturally (reverse)" },
  { on = [ ",", "s" ], run = "sort size --dir-first", desc = "Sort by size" },
  { on = [ ",", "S" ], run = "sort size --reverse --dir-first", desc = "Sort by size (reverse)" },
  { on = [ ",", "m" ], run = "sort modified --dir-first", desc = "Sort by modified" },
  { on = [ ",", "M" ], run = "sort modified --reverse --dir-first", desc = "Sort by modified (reverse)" },
  
  # Mostrar/Ocultar
  { on = [ "." ], run = "hidden toggle", desc = "Toggle hidden files" },
  { on = [ "s" ], run = "linemode size", desc = "Show size" },
  { on = [ "S" ], run = "linemode mtime", desc = "Show modified time" },
  
  # Shell
  { on = [ ";" ], run = "shell", desc = "Open shell" },
  { on = [ ":" ], run = "shell --block", desc = "Open shell (block)" },
  { on = [ "!" ], run = "shell 'nvim' --confirm", desc = "Open Neovim" },
  
  # Navegación rápida
  { on = [ "g", "h" ], run = "cd ~", desc = "Go to home" },
  { on = [ "g", "c" ], run = "cd ~/.config", desc = "Go to config" },
  { on = [ "g", "d" ], run = "cd ~/Downloads", desc = "Go to downloads" },
  { on = [ "g", "D" ], run = "cd ~/Documents", desc = "Go to documents" },
  { on = [ "g", "p" ], run = "cd ~/Projects", desc = "Go to projects" },
  { on = [ "g", "n" ], run = "cd ~/.config/nvim", desc = "Go to Neovim config" },
  
  # Ayuda
  { on = [ "~" ], run = "help", desc = "Help" },
  { on = [ "<F1>" ], run = "help", desc = "Help" },
  
  # Salir
  { on = [ "q" ], run = "quit", desc = "Quit" },
  { on = [ "Q" ], run = "quit --no-cwd-file", desc = "Quit without writing cwd" },
  
  # Tareas
  { on = [ "w" ], run = "tasks_show", desc = "Show tasks" },

  # Funciones personalizadas con tmux
  { on = [ "<C-n>" ], run = "plugin --sync init --args=open_in_tmux_window", desc = "Open window in tmux" },
  { on = [ "<C-p>" ], run = "plugin --sync init --args=open_in_tmux_pane", desc = "Open pane in tmux" },
  { on = [ "<C-t>" ], run = "plugin --sync init --args=open_terminal_window", desc = "Open term in tmux windows" },
  { on = [ "<C-s>" ], run = "plugin --sync init --args=open_terminal_pane", desc = "Open term in tmux pane" },
]

[tasks]
keymap = [
  { on = [ "<Esc>" ], run = "close", desc = "Close task manager" },
  { on = [ "q" ], run = "close", desc = "Close task manager" },
  { on = [ "j" ], run = "arrow 1", desc = "Move cursor down" },
  { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
  { on = [ "<Enter>" ], run = "inspect", desc = "Inspect the task" },
  { on = [ "x" ], run = "cancel", desc = "Cancel the task" },
]

[select]
keymap = [
  { on = [ "<Esc>" ], run = "close", desc = "Cancel selection" },
  { on = [ "q" ], run = "close", desc = "Cancel selection" },
  { on = [ "<Enter>" ], run = "close --submit", desc = "Submit selection" },
  { on = [ "j" ], run = "arrow 1", desc = "Move cursor down" },
  { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
]

[input]
keymap = [
  { on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
  { on = [ "<Enter>" ], run = "close --submit", desc = "Submit input" },
  { on = [ "<C-u>" ], run = "delete --cut", desc = "Delete to start" },
  { on = [ "<C-w>" ], run = "backward --kill", desc = "Delete word backward" },
]

[help]
keymap = [
  { on = [ "<Esc>" ], run = "escape", desc = "Clear filter or close help" },
  { on = [ "q" ], run = "close", desc = "Close help" },
  { on = [ "j" ], run = "arrow 1", desc = "Move cursor down" },
  { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
  { on = [ "/" ], run = "filter", desc = "Filter help" },
]
