# vim:fileencoding=utf-8:foldmethod=marker

# ========================================
# TABS
# ========================================
tab_bar_edge            top
tab_bar_min_tabs        2
tab_bar_margin_height   0 0
tab_bar_margin_width    10
# Use background from Kanagawa Dragon (dark variant)
tab_bar_background      #0d0c0c
# Show user-set title if available, fall back to running command
tab_title_template      "{fmt.noitalic}{fmt.fg.tab}{index} 󱥸 {tab.active_oldest_exe}{activity_symbol}{fmt.fg.red}{bell_symbol}"
active_tab_title_template "{fmt.noitalic}{fmt.fg.tab}{index}  {tab.active_oldest_exe}{activity_symbol}{fmt.fg.red}{bell_symbol}"
tab_bar_style custom
tab_separator ""
